name: Experience for only 2 and a half

on:
  workflow_dispatch:
    inputs:
      duration:
        description: "مدة التشغيل بالدقائق"
        required: true
        default: "170"

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.duration) }}

    steps:
      - name: Install FFmpeg & Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg wget

      - name: Download Logo
        run: |
          wget -O logo.png https://up6.cc/2026/06/178122590817961.png

      - name: Stream 1080p HDR with Large Logo
        run: |
          ffmpeg -re \
            -loglevel warning \
            -stats_period 30 \
            -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36" \
            -referer "https://ostora-tv.hima-sabry2015.workers.dev/" \
            -headers "Origin: https://ostora-tv.hima-sabry2015.workers.dev\r\n" \
            -i "https://worldcup.dzandz496.workers.dev/BNMAX4KHDR.m3u8" \
            -i logo.png \
            -filter_complex "[0:v]scale=1920:1080:flags=lanczos,fps=25,setparams=colorspace=bt2020nc:color_primaries=bt2020:color_trc=smpte2084[bg];[1:v]scale=250:-1[logo];[bg][logo]overlay=W-w-50:H-h-50,format=yuv420p10le" \
            -c:v libx264 \
            -preset veryfast \
            -crf 21 \
            -maxrate 6000k \
            -bufsize 12000k \
            -x264-params "colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:depth=10" \
            -c:a aac -b:a 128k \
            -f flv \
            "rtmp://vsu.okcdn.ru/input/14596556267087_15801691998799_k5vbtvvaju"
