name:  Stream with Logo (170 min) trail only

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 170

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg wget

      - name: Download Logo
        run: |
          wget -O logo.png https://up6.cc/2026/06/178122590817961.png

      - name: Start 1080p HDR Stream with Logo
        run: |
          ffmpeg -re \
            -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
            -referer "https://ostora-tv.hima-sabry2015.workers.dev/" \
            -headers "Origin: https://ostora-tv.hima-sabry2015.workers.dev\r\n" \
            -itsoffset 30 \
            -i "https://worldcup.dzandz496.workers.dev/BNMAX4KHDR.m3u8" \
            -i logo.png \
            -filter_complex "[0:v]scale=1920:1080:flags=lanczos,setparams=colorspace=bt2020nc:color_primaries=bt2020:color_trc=smpte2084[bg];[1:v]scale=300:-1,format=rgba,colorchannelmixer=aa=0.8[logo];[bg][logo]overlay=W-w-40:H-h-40:format=auto,format=yuv420p10le" \
            -c:v libx265 \
            -preset fast \
            -crf 22 \
            -x265-params "colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:depth=10" \
            -c:a aac -b:a 128k \
            -f flv \
            "rtmp://vsu.okcdn.ru/input/14596556267087_15801691998799_k5vbtvvaju"
